### ISSUE TITLE
Every time run this program, It returns "ret: 0xC0000008 (-1073741816)" Then "suspendthread failed GLE: 6"

### ISSUE THREAD

**Issue by howknows** [BreakingMalwareResearch/atom-bombing#7]
My target process is mspaint.exe, and I use windows 10 x64 (build 14393).

**Comment by talliberman** [comment]
First of all our PoC code does not support 64 bit processes. It does support 32 bit processes running on 64 bit systems (WoW).

That being said, the PoC code we released will not work on mspaint.exe.
In order to understand why I'd suggest reading this:
https://breakingmalware.com/injection-techniques/atombombing-cfg-protected-processes/

We will be updating our code soon to include the ability to inject code into CFG protected processes.
